BUILDSCAD_PROJECT=scadUnitConversionLib
BUILDSCAD_VERSION=1.0.0
BUILDSCAD_AUTHOR=dduxx
# this library has no actual assemblies. this simply runs a series of asserts on all the unit
# conversions to test them.
BUILDSCAD_ASSEMBLIES=scad/test/lib/conversion_test.scad
BUILDSCAD_LOG_LEVEL=INFO
BUILDSCAD_OPENSCAD_PATH=openscad
BUILDSCAD_OUTPUT_FORMAT=stl
BUILDSCAD_OPENSCAD_COLORSCHEME=DeepOcean
